// <auto-generated />
using System;
using BethanysPieShopHRM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BethanysPieShopHRM.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250303115629_AddingTimeRegistrationForEmployee")]
    partial class AddingTimeRegistrationForEmployee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BethanysPieShopHRM.Shared.Domain.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            Name = "Belgium"
                        },
                        new
                        {
                            CountryId = 2,
                            Name = "Netherlands"
                        },
                        new
                        {
                            CountryId = 3,
                            Name = "USA"
                        },
                        new
                        {
                            CountryId = 4,
                            Name = "Japan"
                        },
                        new
                        {
                            CountryId = 5,
                            Name = "China"
                        },
                        new
                        {
                            CountryId = 6,
                            Name = "UK"
                        },
                        new
                        {
                            CountryId = 7,
                            Name = "France"
                        },
                        new
                        {
                            CountryId = 8,
                            Name = "Brazil"
                        });
                });

            modelBuilder.Entity("BethanysPieShopHRM.Shared.Domain.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnHoliday")
                        .HasColumnType("bit");

                    b.Property<int?>("JobCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int?>("MaritalStatus")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Smoker")
                        .HasColumnType("bit");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("CountryId");

                    b.HasIndex("JobCategoryId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            BirthDate = new DateTime(1979, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Brussels",
                            Comment = "Lorem Ipsum",
                            CountryId = 1,
                            Email = "bethany@bethanyspieshop.com",
                            FirstName = "Bethany",
                            Gender = 1,
                            IsOnHoliday = false,
                            JobCategoryId = 1,
                            JoinedDate = new DateTime(2015, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Smith",
                            Latitude = 50.850299999999997,
                            Longitude = 4.3517000000000001,
                            MaritalStatus = 1,
                            PhoneNumber = "324777888773",
                            Smoker = false,
                            Street = "Grote Markt 1",
                            Zip = "1000"
                        });
                });

            modelBuilder.Entity("BethanysPieShopHRM.Shared.Domain.JobCategory", b =>
                {
                    b.Property<int>("JobCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobCategoryId"));

                    b.Property<string>("JobCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobCategoryId");

                    b.ToTable("JobCategories");

                    b.HasData(
                        new
                        {
                            JobCategoryId = 1,
                            JobCategoryName = "Pie research"
                        },
                        new
                        {
                            JobCategoryId = 2,
                            JobCategoryName = "Sales"
                        },
                        new
                        {
                            JobCategoryId = 3,
                            JobCategoryName = "Management"
                        },
                        new
                        {
                            JobCategoryId = 4,
                            JobCategoryName = "Store staff"
                        },
                        new
                        {
                            JobCategoryId = 5,
                            JobCategoryName = "Finance"
                        },
                        new
                        {
                            JobCategoryId = 6,
                            JobCategoryName = "QA"
                        },
                        new
                        {
                            JobCategoryId = 7,
                            JobCategoryName = "IT"
                        },
                        new
                        {
                            JobCategoryId = 8,
                            JobCategoryName = "Cleaning"
                        },
                        new
                        {
                            JobCategoryId = 9,
                            JobCategoryName = "Bakery"
                        });
                });

            modelBuilder.Entity("BethanysPieShopHRM.Shared.Domain.TimeRegistration", b =>
                {
                    b.Property<int>("TimeRegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeRegistrationId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PerformedTaskDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("TimeRegistrationId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("TimeRegistrations");

                    b.HasData(
                        new
                        {
                            TimeRegistrationId = 2,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 1, 24, 22, 16, 53, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 2",
                            StartTime = new DateTime(2024, 3, 27, 6, 44, 47, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 3,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 6, 3, 14, 12, 59, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 3",
                            StartTime = new DateTime(2024, 2, 1, 7, 42, 49, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 4,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 4, 4, 3, 39, 1, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 4",
                            StartTime = new DateTime(2024, 7, 14, 14, 54, 13, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 5,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 11, 24, 23, 1, 26, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 5",
                            StartTime = new DateTime(2024, 9, 2, 8, 26, 48, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 6,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 5, 16, 8, 1, 3, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 6",
                            StartTime = new DateTime(2024, 3, 11, 2, 40, 23, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 7,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 6, 5, 22, 10, 40, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 7",
                            StartTime = new DateTime(2024, 7, 14, 0, 1, 13, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 8,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 9, 20, 10, 28, 36, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 8",
                            StartTime = new DateTime(2024, 3, 18, 6, 5, 7, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 9,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 11, 25, 20, 36, 8, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 9",
                            StartTime = new DateTime(2024, 7, 21, 10, 12, 19, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 10,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 8, 2, 17, 32, 8, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 10",
                            StartTime = new DateTime(2024, 3, 18, 10, 51, 44, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 11,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 5, 1, 6, 37, 48, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 11",
                            StartTime = new DateTime(2024, 10, 10, 22, 6, 7, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 12,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 6, 9, 3, 0, 45, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 12",
                            StartTime = new DateTime(2024, 9, 24, 8, 39, 46, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 13,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 9, 10, 23, 58, 2, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 13",
                            StartTime = new DateTime(2024, 9, 30, 1, 4, 5, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 14,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 1, 25, 9, 8, 31, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 14",
                            StartTime = new DateTime(2024, 12, 2, 22, 34, 48, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 15,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 5, 12, 16, 19, 12, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 15",
                            StartTime = new DateTime(2024, 1, 23, 10, 36, 26, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 16,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 12, 10, 1, 4, 9, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 16",
                            StartTime = new DateTime(2024, 10, 28, 16, 55, 37, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 17,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 10, 24, 15, 33, 15, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 17",
                            StartTime = new DateTime(2024, 10, 8, 20, 24, 56, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 18,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 1, 21, 10, 17, 32, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 18",
                            StartTime = new DateTime(2024, 11, 2, 2, 39, 29, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 19,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 2, 25, 18, 7, 49, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 19",
                            StartTime = new DateTime(2024, 9, 10, 21, 22, 50, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 20,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 8, 9, 9, 3, 36, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 20",
                            StartTime = new DateTime(2024, 6, 11, 7, 12, 31, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 21,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 8, 13, 2, 41, 57, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 21",
                            StartTime = new DateTime(2024, 11, 21, 14, 58, 21, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 22,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 10, 20, 0, 35, 48, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 22",
                            StartTime = new DateTime(2024, 1, 31, 14, 20, 52, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 23,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 11, 20, 20, 45, 41, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 23",
                            StartTime = new DateTime(2024, 12, 27, 5, 20, 24, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 24,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 10, 8, 13, 9, 58, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 24",
                            StartTime = new DateTime(2024, 8, 1, 15, 23, 42, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 25,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 6, 9, 6, 29, 47, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 25",
                            StartTime = new DateTime(2024, 5, 9, 15, 50, 49, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 26,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 4, 2, 5, 42, 46, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 26",
                            StartTime = new DateTime(2024, 2, 24, 21, 41, 37, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 27,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 10, 3, 4, 6, 48, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 27",
                            StartTime = new DateTime(2024, 8, 4, 20, 47, 39, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 28,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 8, 20, 0, 45, 36, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 28",
                            StartTime = new DateTime(2024, 1, 10, 0, 39, 8, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 29,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 3, 29, 4, 20, 9, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 29",
                            StartTime = new DateTime(2024, 10, 29, 10, 18, 20, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 30,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 6, 20, 7, 23, 55, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 30",
                            StartTime = new DateTime(2024, 10, 28, 19, 55, 13, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 31,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 9, 26, 14, 16, 14, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 31",
                            StartTime = new DateTime(2024, 5, 13, 8, 17, 53, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 32,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 7, 8, 20, 5, 11, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 32",
                            StartTime = new DateTime(2024, 5, 11, 16, 20, 19, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 33,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 5, 5, 2, 56, 59, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 33",
                            StartTime = new DateTime(2024, 11, 21, 13, 19, 5, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 34,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 11, 6, 14, 23, 13, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 34",
                            StartTime = new DateTime(2024, 2, 21, 8, 54, 9, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 35,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 7, 23, 9, 13, 11, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 35",
                            StartTime = new DateTime(2024, 2, 26, 5, 31, 43, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 36,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 6, 8, 10, 47, 6, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 36",
                            StartTime = new DateTime(2024, 9, 10, 9, 55, 22, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 37,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 3, 30, 14, 28, 14, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 37",
                            StartTime = new DateTime(2024, 3, 11, 1, 31, 34, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 38,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 7, 7, 12, 32, 0, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 38",
                            StartTime = new DateTime(2024, 11, 30, 14, 5, 44, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 39,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 6, 28, 4, 50, 45, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 39",
                            StartTime = new DateTime(2024, 3, 24, 8, 39, 45, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 40,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 12, 16, 15, 33, 14, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 40",
                            StartTime = new DateTime(2024, 3, 26, 13, 43, 49, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 41,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 8, 30, 17, 39, 46, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 41",
                            StartTime = new DateTime(2024, 9, 18, 17, 52, 51, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 42,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 10, 30, 7, 48, 59, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 42",
                            StartTime = new DateTime(2024, 12, 29, 3, 53, 5, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 43,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 11, 22, 7, 21, 2, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 43",
                            StartTime = new DateTime(2024, 4, 9, 12, 35, 7, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 44,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 1, 28, 16, 58, 43, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 44",
                            StartTime = new DateTime(2024, 5, 21, 7, 1, 33, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 45,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 1, 26, 19, 32, 1, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 45",
                            StartTime = new DateTime(2024, 8, 30, 17, 22, 6, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 46,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 5, 19, 16, 41, 21, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 46",
                            StartTime = new DateTime(2024, 10, 18, 16, 56, 50, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 47,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 7, 5, 2, 44, 10, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 47",
                            StartTime = new DateTime(2024, 3, 13, 23, 22, 38, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 48,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 4, 4, 19, 58, 12, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 48",
                            StartTime = new DateTime(2024, 4, 22, 5, 31, 7, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 49,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 3, 8, 16, 3, 40, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 49",
                            StartTime = new DateTime(2024, 1, 16, 11, 8, 25, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 50,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 7, 19, 21, 57, 39, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 50",
                            StartTime = new DateTime(2024, 10, 3, 2, 4, 6, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 51,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 11, 7, 2, 51, 22, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 51",
                            StartTime = new DateTime(2024, 4, 7, 5, 52, 31, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 52,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 2, 8, 0, 58, 54, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 52",
                            StartTime = new DateTime(2024, 9, 16, 6, 3, 28, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 53,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 1, 16, 22, 16, 46, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 53",
                            StartTime = new DateTime(2024, 8, 7, 21, 28, 49, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 54,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 10, 9, 9, 10, 16, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 54",
                            StartTime = new DateTime(2024, 9, 29, 19, 39, 33, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 55,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 6, 18, 22, 26, 29, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 55",
                            StartTime = new DateTime(2024, 12, 12, 7, 12, 22, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 56,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 8, 24, 10, 26, 38, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 56",
                            StartTime = new DateTime(2024, 11, 8, 13, 3, 11, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 57,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 1, 23, 8, 24, 36, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 57",
                            StartTime = new DateTime(2024, 2, 15, 13, 24, 13, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 58,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 3, 24, 22, 34, 21, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 58",
                            StartTime = new DateTime(2024, 12, 9, 16, 41, 3, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 59,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 2, 14, 22, 25, 19, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 59",
                            StartTime = new DateTime(2024, 9, 21, 7, 7, 29, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 60,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 4, 15, 23, 13, 23, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 60",
                            StartTime = new DateTime(2024, 10, 27, 13, 40, 21, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 61,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 9, 13, 10, 25, 49, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 61",
                            StartTime = new DateTime(2024, 11, 4, 15, 51, 57, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 62,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 4, 10, 0, 7, 47, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 62",
                            StartTime = new DateTime(2024, 10, 8, 6, 42, 40, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 63,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 1, 28, 10, 2, 24, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 63",
                            StartTime = new DateTime(2024, 12, 24, 13, 10, 52, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 64,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 8, 12, 0, 58, 0, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 64",
                            StartTime = new DateTime(2024, 10, 5, 7, 30, 29, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 65,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 12, 24, 17, 29, 26, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 65",
                            StartTime = new DateTime(2024, 4, 2, 4, 52, 56, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 66,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 10, 9, 13, 7, 49, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 66",
                            StartTime = new DateTime(2024, 1, 22, 4, 47, 37, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 67,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 1, 1, 8, 42, 27, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 67",
                            StartTime = new DateTime(2024, 10, 23, 20, 12, 3, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 68,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 6, 27, 20, 42, 34, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 68",
                            StartTime = new DateTime(2024, 11, 18, 23, 8, 41, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 69,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 6, 24, 11, 14, 34, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 69",
                            StartTime = new DateTime(2024, 10, 6, 0, 6, 30, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 70,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 11, 25, 8, 33, 55, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 70",
                            StartTime = new DateTime(2024, 5, 5, 6, 18, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 71,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 10, 12, 4, 43, 19, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 71",
                            StartTime = new DateTime(2024, 7, 23, 22, 45, 3, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 72,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 5, 1, 6, 54, 43, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 72",
                            StartTime = new DateTime(2024, 4, 21, 5, 8, 14, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 73,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 4, 24, 2, 55, 22, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 73",
                            StartTime = new DateTime(2024, 3, 29, 2, 1, 55, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 74,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 3, 20, 12, 27, 42, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 74",
                            StartTime = new DateTime(2024, 1, 26, 0, 45, 41, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 75,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 4, 19, 14, 33, 54, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 75",
                            StartTime = new DateTime(2024, 11, 3, 4, 39, 18, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 76,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 4, 5, 18, 47, 19, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 76",
                            StartTime = new DateTime(2024, 10, 17, 17, 7, 1, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 77,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 7, 28, 9, 51, 49, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 77",
                            StartTime = new DateTime(2024, 3, 30, 7, 18, 1, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 78,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 8, 21, 0, 55, 50, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 78",
                            StartTime = new DateTime(2024, 4, 11, 3, 23, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 79,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 10, 22, 13, 11, 54, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 79",
                            StartTime = new DateTime(2024, 1, 3, 15, 30, 21, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 80,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 3, 25, 18, 46, 55, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 80",
                            StartTime = new DateTime(2024, 6, 18, 10, 28, 21, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 81,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 8, 8, 2, 37, 13, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 81",
                            StartTime = new DateTime(2024, 12, 29, 0, 11, 25, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 82,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 3, 7, 19, 17, 13, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 82",
                            StartTime = new DateTime(2024, 7, 2, 12, 18, 30, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 83,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 5, 25, 10, 24, 14, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 83",
                            StartTime = new DateTime(2024, 10, 17, 5, 5, 33, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 84,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 7, 7, 15, 23, 27, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 84",
                            StartTime = new DateTime(2024, 3, 26, 6, 27, 27, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 85,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 4, 3, 5, 20, 47, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 85",
                            StartTime = new DateTime(2024, 9, 26, 20, 59, 40, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 86,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 6, 23, 22, 42, 52, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 86",
                            StartTime = new DateTime(2024, 3, 1, 19, 43, 53, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 87,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 7, 21, 22, 51, 59, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 87",
                            StartTime = new DateTime(2024, 2, 21, 0, 36, 27, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 88,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 11, 24, 12, 27, 3, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 88",
                            StartTime = new DateTime(2024, 11, 2, 5, 52, 38, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 89,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 4, 28, 2, 34, 25, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 89",
                            StartTime = new DateTime(2024, 8, 30, 7, 6, 34, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 90,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 6, 5, 15, 10, 58, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 90",
                            StartTime = new DateTime(2024, 6, 16, 7, 39, 28, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 91,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 10, 8, 10, 58, 31, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 91",
                            StartTime = new DateTime(2024, 12, 15, 7, 1, 23, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 92,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 10, 19, 19, 29, 42, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 92",
                            StartTime = new DateTime(2024, 9, 6, 4, 0, 17, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 93,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 4, 14, 10, 53, 31, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 93",
                            StartTime = new DateTime(2024, 2, 22, 18, 54, 46, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 94,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 6, 23, 23, 33, 13, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 94",
                            StartTime = new DateTime(2024, 1, 13, 15, 26, 26, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 95,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 8, 22, 22, 23, 29, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 95",
                            StartTime = new DateTime(2024, 2, 25, 20, 23, 22, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 96,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 11, 8, 20, 4, 26, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 96",
                            StartTime = new DateTime(2024, 10, 10, 3, 37, 17, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 97,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 6, 30, 8, 0, 1, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 97",
                            StartTime = new DateTime(2024, 4, 27, 16, 20, 35, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 98,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 8, 5, 14, 35, 19, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 98",
                            StartTime = new DateTime(2024, 6, 1, 6, 31, 28, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 99,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 12, 29, 23, 7, 48, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 99",
                            StartTime = new DateTime(2024, 1, 30, 13, 2, 25, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TimeRegistrationId = 100,
                            EmployeeId = 1,
                            EndTime = new DateTime(2024, 3, 13, 0, 14, 47, 0, DateTimeKind.Unspecified),
                            PerformedTaskDescription = "Task 100",
                            StartTime = new DateTime(2024, 4, 27, 15, 54, 48, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BethanysPieShopHRM.Shared.Domain.Employee", b =>
                {
                    b.HasOne("BethanysPieShopHRM.Shared.Domain.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("BethanysPieShopHRM.Shared.Domain.JobCategory", "JobCategory")
                        .WithMany()
                        .HasForeignKey("JobCategoryId");

                    b.Navigation("Country");

                    b.Navigation("JobCategory");
                });

            modelBuilder.Entity("BethanysPieShopHRM.Shared.Domain.TimeRegistration", b =>
                {
                    b.HasOne("BethanysPieShopHRM.Shared.Domain.Employee", null)
                        .WithMany("TimeRegistration")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BethanysPieShopHRM.Shared.Domain.Employee", b =>
                {
                    b.Navigation("TimeRegistration");
                });
#pragma warning restore 612, 618
        }
    }
}
